<?php

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 */
function psi_preprocess_html(&$variables) {
      $config = \Drupal::config('psi.configure');
      //$selected_theme = $config->get('scroll_progress_theme');
      $colour = $config->get('scroll_progress_color');
     // $selected_admin = $config->get('scroll_progress_load_on_admin_enabled');
       $variables['#attached']['drupalSettings']['psi']['colour'] = $colour;
       $variables['#attached']['library'][] = 'psi/psi.script';
       $variables['#attached']['library'][] = 'psi/psi.theme';

}
