<?php

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 */
function psi_preprocess_html(&$variables) {
      $config = \Drupal::config('psi.configure');
      $selected_theme = $config->get('scroll_progress_theme');
      $colour = $config->get('scroll_progress_color');
     // $selected_admin = $config->get('scroll_progress_load_on_admin_enabled');
       $variables['#attached']['drupalSettings']['psi']['colour'] = $colour;

 if ($selected_theme == 1) {
    $variables['#attached']['library'][] = 'psi/page_scroll_indicator_line';
  }
 if ($selected_theme == 2) {
     $variables['#attached']['library'][] = 'psi/page_scroll_indicator_circular';
  }


//       $variables['#attached']['library'][] = 'psi/page_scroll_indicator_line';
  //     $variables['#attached']['library'][] = 'psi/page_scroll_indicator_circular';
    //   $variables['#attached']['library'][] = 'psi/page_scroll_indicator_line';
      // $variables['#attached']['library'][] = 'psi/page_scroll_indicator_circular';


}
